comittttt

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,14 +14,16 @@ jobs:
     
     - name: install package.json
       run: npm install
+
+    - name: Run tests
+      run: npm test
     
-    - name: Run Test1
-      run: |
-        output=$(node dist/Test1.js)
-        exit_code=$output
+    # - name: Run Test1
+    #   run: |
+    #     output=$(node dist/Test1.js)
+    #     exit_code=$output
 
-        if [ $exit_code -ne 0 ]; then
-          echo "Error $exit_code"
-          exit 1
-        fi
-
+    #     if [ $exit_code -ne 0 ]; then
+    #       echo "Error $exit_code"
+    #       exit 1
+    #     fi
